## Tensors


In [1]:
# scalers and vectors are named in lowercase 
# higher order tensors are named in uppercase
# this is not a strict rule but a good practice to follow

In [2]:
import torch

In [3]:
# scalars
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item(),type(scalar.item())

(7, int)

In [6]:
# vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# matrix
x=[[1,2,3],
   [4,5,6]]
MATRIX=torch.tensor(x)
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
MATRIX[0]

tensor([1, 2, 3])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 3])

In [13]:
MATRIX.size()

torch.Size([2, 3])

In [14]:
x=[[[1,2,3],
    [4,5,6]],
   [[7,8,9],
    [10,11,12]]]
TENSOR3D=torch.tensor(x)
TENSOR3D

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [15]:
TENSOR3D.ndim

3

In [16]:
TENSOR3D.shape

torch.Size([2, 2, 3])

In [17]:
TENSOR3D.size()

torch.Size([2, 2, 3])

## Random Tensors

In [18]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.2192, 0.7781, 0.9750, 0.4247],
        [0.3229, 0.8064, 0.6221, 0.4759],
        [0.4802, 0.5121, 0.9372, 0.0920]])

In [19]:
random_tensor.ndim

2

In [20]:
random_tensor.shape

torch.Size([3, 4])

In [21]:
torch.rand(1,2,2)

tensor([[[0.8976, 0.8147],
         [0.6247, 0.4795]]])

In [22]:
# creating a random tensor with similar shape to an image tensor
image_tensor = torch.rand(size=(3, 224, 224))
image_tensor

tensor([[[0.9606, 0.8077, 0.1795,  ..., 0.1423, 0.6261, 0.9385],
         [0.2530, 0.6612, 0.0098,  ..., 0.0523, 0.2908, 0.3211],
         [0.9647, 0.0275, 0.1365,  ..., 0.5400, 0.5330, 0.1680],
         ...,
         [0.3467, 0.0029, 0.8551,  ..., 0.5918, 0.6171, 0.0253],
         [0.7132, 0.2193, 0.2384,  ..., 0.9378, 0.2766, 0.8560],
         [0.5517, 0.2822, 0.1954,  ..., 0.1204, 0.2437, 0.0612]],

        [[0.7792, 0.6658, 0.7528,  ..., 0.8052, 0.8015, 0.8968],
         [0.0437, 0.1884, 0.8386,  ..., 0.8949, 0.6959, 0.0788],
         [0.0745, 0.2010, 0.8626,  ..., 0.0974, 0.5320, 0.0660],
         ...,
         [0.6408, 0.7107, 0.7375,  ..., 0.3339, 0.8035, 0.9549],
         [0.1116, 0.5258, 0.0562,  ..., 0.4886, 0.8591, 0.9986],
         [0.7406, 0.1566, 0.7288,  ..., 0.2674, 0.0282, 0.5514]],

        [[0.5767, 0.7760, 0.9665,  ..., 0.9209, 0.6577, 0.8936],
         [0.2920, 0.9403, 0.1534,  ..., 0.3429, 0.8243, 0.4228],
         [0.2732, 0.8409, 0.5618,  ..., 0.8108, 0.6230, 0.

## Zeros and Ones

In [23]:
zeros=torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
ones=torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

## creating a range of tensors and tensors like

In [26]:
torch.range(0, 10)

C:\Users\miyas\AppData\Local\Temp\ipykernel_11972\1549641488.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [27]:
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
torch.arange(start=1, end=10, step=2)

tensor([1, 3, 5, 7, 9])

In [29]:
torch.range(start=1, end=10, step=2)

C:\Users\miyas\AppData\Local\Temp\ipykernel_11972\2770446362.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(start=1, end=10, step=2)


tensor([1., 3., 5., 7., 9.])

In [30]:
# creating tensors like 
ones=torch.ones(size=(3, 3))
torch.zeros_like(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## tensor datatypes

In [31]:
x=torch.tensor([1,2,3],dtype=None)
x,x.dtype

(tensor([1, 2, 3]), torch.int64)

In [32]:
x=torch.tensor([1,2.1,3],dtype=None,device=None,requires_grad=False)
x,x.dtype

(tensor([1.0000, 2.1000, 3.0000]), torch.float32)

In [33]:
x=torch.tensor([1,2,3],dtype=torch.float32)
x,x.dtype

(tensor([1., 2., 3.]), torch.float32)

In [34]:
x=x.type(torch.float16)
x,x.dtype

(tensor([1., 2., 3.], dtype=torch.float16), torch.float16)

In [35]:
x=x.type(torch.float32)
x=x.type(torch.half)
x,x.dtype

(tensor([1., 2., 3.], dtype=torch.float16), torch.float16)

In [36]:
x=x.type(torch.float32)
x=x.type(torch.double)
x,x.dtype

(tensor([1., 2., 3.], dtype=torch.float64), torch.float64)

In [37]:
x=x.type(torch.float32)
x=x.type(torch.double)
x,x.dtype

(tensor([1., 2., 3.], dtype=torch.float64), torch.float64)

In [38]:
a=torch.tensor([1,2,3],dtype=torch.float32)
b=torch.tensor([1,2,3],dtype=torch.half)
a*b,(a*b).dtype

(tensor([1., 4., 9.]), torch.float32)

## getting information for tensors 

In [39]:
x.device

device(type='cpu')

In [40]:
x.ndim

1

In [41]:
x.shape

torch.Size([3])

In [42]:
x.dtype

torch.float64

In [43]:
x.size()

torch.Size([3])

In [44]:
print(x)

tensor([1., 2., 3.], dtype=torch.float64)


# manupulating tensors

In [45]:
a=torch.tensor([1,2,3],dtype=torch.float32)
b=torch.tensor([5,6,3],dtype=torch.float32)
x=torch.rand(3,4)
y=torch.rand(3,4)
print(f" a = {a},\n b = {b},\n x = {x},\n y = {y}")

 a = tensor([1., 2., 3.]),
 b = tensor([5., 6., 3.]),
 x = tensor([[2.9807e-01, 8.8774e-01, 9.3055e-04, 5.1217e-01],
        [9.0563e-01, 7.3605e-01, 2.7902e-01, 9.9995e-01],
        [5.5775e-01, 4.9695e-01, 6.4946e-01, 6.8689e-01]]),
 y = tensor([[0.1205, 0.4716, 0.6552, 0.5526],
        [0.9388, 0.2836, 0.8534, 0.5179],
        [0.6020, 0.5905, 0.3818, 0.3183]])


In [46]:
# addition
a+b

tensor([6., 8., 6.])

In [47]:
x+y

tensor([[0.4185, 1.3594, 0.6562, 1.0648],
        [1.8444, 1.0196, 1.1324, 1.5178],
        [1.1598, 1.0874, 1.0312, 1.0052]])

In [48]:
x+10

tensor([[10.2981, 10.8877, 10.0009, 10.5122],
        [10.9056, 10.7360, 10.2790, 10.9999],
        [10.5578, 10.4969, 10.6495, 10.6869]])

In [49]:
a+10

tensor([11., 12., 13.])

In [50]:
torch.add(a,10)

tensor([11., 12., 13.])

In [51]:
# subtraction
b-a

tensor([4., 4., 0.])

In [52]:
x-y

tensor([[ 0.1776,  0.4161, -0.6543, -0.0404],
        [-0.0332,  0.4525, -0.5744,  0.4821],
        [-0.0442, -0.0935,  0.2677,  0.3686]])

In [53]:
a-1

tensor([0., 1., 2.])

In [54]:
x-1

tensor([[-7.0193e-01, -1.1226e-01, -9.9907e-01, -4.8783e-01],
        [-9.4370e-02, -2.6395e-01, -7.2098e-01, -5.3823e-05],
        [-4.4225e-01, -5.0305e-01, -3.5054e-01, -3.1311e-01]])

In [55]:
# multiplication
a*b

tensor([ 5., 12.,  9.])

In [56]:
torch.mul(a,b)

tensor([ 5., 12.,  9.])

In [57]:
a*10

tensor([10., 20., 30.])

In [58]:
torch.mul(a,10)

tensor([10., 20., 30.])

###  matrix multiplication


In [59]:
# element wise mulitplication
x,x*2

(tensor([[2.9807e-01, 8.8774e-01, 9.3055e-04, 5.1217e-01],
         [9.0563e-01, 7.3605e-01, 2.7902e-01, 9.9995e-01],
         [5.5775e-01, 4.9695e-01, 6.4946e-01, 6.8689e-01]]),
 tensor([[5.9615e-01, 1.7755e+00, 1.8611e-03, 1.0243e+00],
         [1.8113e+00, 1.4721e+00, 5.5803e-01, 1.9999e+00],
         [1.1155e+00, 9.9390e-01, 1.2989e+00, 1.3738e+00]]))

In [60]:
x**2

tensor([[8.8848e-02, 7.8808e-01, 8.6592e-07, 2.6232e-01],
        [8.2017e-01, 5.4177e-01, 7.7851e-02, 9.9989e-01],
        [3.1109e-01, 2.4696e-01, 4.2180e-01, 4.7182e-01]])

In [61]:
a

tensor([1., 2., 3.])

In [62]:
a*a

tensor([1., 4., 9.])

In [63]:
a**2

tensor([1., 4., 9.])

In [64]:
a*a*a

tensor([ 1.,  8., 27.])

In [65]:
a**3

tensor([ 1.,  8., 27.])

In [66]:
x*y

tensor([[3.5908e-02, 4.1870e-01, 6.0973e-04, 2.8302e-01],
        [8.5021e-01, 2.0872e-01, 2.3811e-01, 5.1786e-01],
        [3.3577e-01, 2.9345e-01, 2.4795e-01, 2.1861e-01]])

In [67]:
torch.matmul(x,y.T)

tensor([[0.7382, 0.7976, 0.8670],
        [1.1916, 1.8149, 1.4046],
        [1.1067, 1.5745, 1.0958]])

In [68]:
x*y # element wise multiplication

tensor([[3.5908e-02, 4.1870e-01, 6.0973e-04, 2.8302e-01],
        [8.5021e-01, 2.0872e-01, 2.3811e-01, 5.1786e-01],
        [3.3577e-01, 2.9345e-01, 2.4795e-01, 2.1861e-01]])

In [69]:
torch.matmul(x,y.T)

tensor([[0.7382, 0.7976, 0.8670],
        [1.1916, 1.8149, 1.4046],
        [1.1067, 1.5745, 1.0958]])

In [70]:
x@y.T

tensor([[0.7382, 0.7976, 0.8670],
        [1.1916, 1.8149, 1.4046],
        [1.1067, 1.5745, 1.0958]])

In [71]:
torch.mul(a,b)

tensor([ 5., 12.,  9.])

In [72]:
torch.matmul(a,b)

tensor(26.)

## aggregation

In [73]:
# x=torch.tensor([1,2,3],dtype=torch.int64) # for calculating mean we need it to be float32 or float64 
x=torch.tensor([1,2,3],dtype=torch.float32) 
y=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)

In [74]:
torch.min(x),torch.max(x)

(tensor(1.), tensor(3.))

In [75]:
x.min(),x.max()

(tensor(1.), tensor(3.))

In [76]:
torch.argmin(x),torch.argmax(x)

(tensor(0), tensor(2))

In [77]:
torch.min(y),torch.max(y)

(tensor(1.), tensor(6.))

In [78]:
y.min(),y.max()

(tensor(1.), tensor(6.))

In [79]:
torch.argmax(y),torch.argmin(y)

(tensor(5), tensor(0))

In [80]:
torch.mean(x),torch.mean(y)

(tensor(2.), tensor(3.5000))

In [81]:
x.type(torch.float32).mean()

tensor(2.)

In [82]:
torch.sum(x),x.sum()

(tensor(6.), tensor(6.))

In [83]:
torch.sum(y),y.sum()

(tensor(21.), tensor(21.))

In [84]:
torch.sum(y,axis=0),y.sum(axis=0)

(tensor([5., 7., 9.]), tensor([5., 7., 9.]))

In [85]:
torch.sum(y,axis=1),y.sum(axis=1)

(tensor([ 6., 15.]), tensor([ 6., 15.]))

## reshaping,viewing, stacking, sqeezing and unsqueezing of tensors

In [86]:
# reshaping -> reshapes the input tensor to a defined shape and also make change in memory
# view -> reshapes the input tensor to a defined shape but does not make change in memory
# stacking -> stacking tensors on top of each other
# squeeize -> removes all the dimensions of size 1
# unsqueeze -> adds a dimension of size 1 at a specified position
# permute -> rearranges the dimensions of a tensor in a specified order

In [87]:
x=torch.arange(1.,11.)
x,x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [88]:
x_reshaped=x.reshape(2,5)
x_reshaped,x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [89]:
# changing the value in reshaped will not change the value in memory
x_reshaped[0][0]=100
x,x_reshaped  # here x_reshaped is not forced to copy thats why changing the value also changes the value in x

(tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]),
 tensor([[100.,   2.,   3.,   4.,   5.],
         [  6.,   7.,   8.,   9.,  10.]]))

In [90]:
# tracking back x
x[0]=1
x


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [91]:
# changing the view
z=x.view(2,5)
z,z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [92]:
# changing value in view will change the original tensor
z[0][0]=100
x,z

(tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]),
 tensor([[100.,   2.,   3.,   4.,   5.],
         [  6.,   7.,   8.,   9.,  10.]]))

In [93]:
# stacking
torch.stack([x,x,x],dim=0)

tensor([[100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
        [100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
        [100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]])

In [94]:
torch.vstack([x,x,x])

tensor([[100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
        [100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
        [100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]])

In [95]:
torch.stack([x,x,x],dim=1)


tensor([[100., 100., 100.],
        [  2.,   2.,   2.],
        [  3.,   3.,   3.],
        [  4.,   4.,   4.],
        [  5.,   5.,   5.],
        [  6.,   6.,   6.],
        [  7.,   7.,   7.],
        [  8.,   8.,   8.],
        [  9.,   9.,   9.],
        [ 10.,  10.,  10.]])

In [96]:
torch.hstack([x,x,x,torch.arange(15,19)])

tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10., 100.,   2.,
          3.,   4.,   5.,   6.,   7.,   8.,   9.,  10., 100.,   2.,   3.,   4.,
          5.,   6.,   7.,   8.,   9.,  10.,  15.,  16.,  17.,  18.])

In [97]:
# squeeze
x=torch.arange(1.,10.).reshape(1,3,3,1)
x

tensor([[[[1.],
          [2.],
          [3.]],

         [[4.],
          [5.],
          [6.]],

         [[7.],
          [8.],
          [9.]]]])

In [98]:
torch.squeeze(torch.squeeze(x)),torch.squeeze(x).shape


(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [99]:
x.squeeze(),x.squeeze().shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [100]:
y=x.squeeze()
y

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [101]:
y=y.reshape(9,1)
y.squeeze(),y.squeeze().shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [102]:
x=torch.arange(1.,10.).reshape(1,1,3,3,1)
x_squeezed=torch.squeeze(x)
x_squeezed,x_squeezed.shape #it removes all the dimensions of size 1

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [103]:
x_unsqueeze=x_squeezed.unsqueeze(dim=0)
x_unsqueeze,x_unsqueeze.shape #it adds a dimension of size 1 at the specified position

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.Size([1, 3, 3]))

In [104]:
x_unsqueeze=x_squeezed.unsqueeze(dim=1)
x_unsqueeze,x_unsqueeze.shape #it adds a dimension of size 1 at the specified position

(tensor([[[1., 2., 3.]],
 
         [[4., 5., 6.]],
 
         [[7., 8., 9.]]]),
 torch.Size([3, 1, 3]))

In [105]:
x=torch.arange(1.,10.).reshape(1,3,3)
x,x.shape

(tensor([[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]]),
 torch.Size([1, 3, 3]))

In [106]:
x.permute(2,0,1),x.permute(2,0,1).shape #it rearranges the dimensions of a tensor in a specified order

(tensor([[[1., 4., 7.]],
 
         [[2., 5., 8.]],
 
         [[3., 6., 9.]]]),
 torch.Size([3, 1, 3]))

In [107]:
# images
x_original=torch.rand(size=(224,224,3)) #(height,width,channels)
x_original.shape
x_image=torch.permute(x_original,(2,0,1)) # rearranging the dimensions to (channels,height,width) which is the common format for image tensors in deep learning

x_image.shape

torch.Size([3, 224, 224])

## indexing data from tensors

In [108]:
x=torch.arange(1.,10.).reshape(1,3,3)
x

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])

In [109]:
x[0]

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [110]:
x[0][0],x[0,0]

(tensor([1., 2., 3.]), tensor([1., 2., 3.]))

In [111]:
x[0][0][-1],x[0,0,-1]

(tensor(3.), tensor(3.))

In [112]:
x[0,:,1]

tensor([2., 5., 8.])

In [113]:
x[0,-1,:]

tensor([7., 8., 9.])

## numpy array to tensor

In [114]:
import numpy as np

In [115]:
x=np.array([1,2,3])
tensor=torch.from_numpy(x)
tensor,tensor.dtype

(tensor([1, 2, 3]), torch.int64)

In [116]:
x=x+1
x,tensor

(array([2, 3, 4]), tensor([1, 2, 3]))

In [117]:
tensor=torch.arange(start=1,end=10.0,step=2)
array=tensor.numpy()
array

array([1., 3., 5., 7., 9.], dtype=float32)

In [118]:
tensor=tensor+1
tensor,array

(tensor([ 2.,  4.,  6.,  8., 10.]), array([1., 3., 5., 7., 9.], dtype=float32))

## Reproducibility

In [119]:
torch.rand(3,4),torch.rand(3,4)


(tensor([[0.4451, 0.6161, 0.6353, 0.0422],
         [0.9990, 0.4687, 0.8717, 0.4641],
         [0.9143, 0.9374, 0.8216, 0.8833]]),
 tensor([[0.7263, 0.5258, 0.3470, 0.1317],
         [0.4389, 0.7520, 0.7654, 0.2208],
         [0.3081, 0.1180, 0.1282, 0.9512]]))

In [120]:
# to reduce the randomness in NN there comes the concept of random seed which is used to set the random state of the model to a fixed value so that we can reproduce the results

# random but reproducible results
torch.manual_seed(42)
torch.rand(3,4),torch.rand(3,4)

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]))

## running tensors on gpu

In [121]:
torch.cuda.is_available()

True

In [122]:
device='cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [123]:
tensor

tensor([ 2.,  4.,  6.,  8., 10.])

In [124]:
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([ 2.,  4.,  6.,  8., 10.], device='cuda:0')

In [125]:
# if the tensor is in gpu then we cant convert to numpy array directly, we need to move it to cpu first and then convert to numpy array
tensor_on_cpu=tensor_on_gpu.cpu()
numpy_array=tensor_on_cpu.detach().numpy() 